### ISSUE TITLE
Timeouts on Vicuna/OpenAI are not correctly caught

### ISSUE THREAD

**Issue by gciatto** [Chistera4-Expectation/kg-filler#1]
```
2024-02-19 09:39:25,156 - kgfiller - DEBUG - Caching query `OpenAiQuery(question='instances list for class Food Dressing, names only', model='vicuna', limit=100, attempt=None, background="You're a dietician")` into file /kgfiller/data/cache-1c398256a56f497af158ad49ad4dda8b58f20b4c30f8753e48248ef8571de299.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ff5db9c0410>, 'Connection to clusters.almaai.unibo.it timed out. (connect timeout=600)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='clusters.almaai.unibo.it', port=23231): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff5db9c0410>, 'Connection to clusters.almaai.unibo.it timed out. (connect timeout=600)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 520, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='clusters.almaai.unibo.it', port=23231): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff5db9c0410>, 'Connection to clusters.almaai.unibo.it timed out. (connect timeout=600)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/kgfiller/kgfiller/__main__.py", line 32, in <module>
    commit = find_instances_for_class(kg, cls, instance_queries)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 164, in find_instances_for_class
    return _make_queries(kg, queries, FindInstancesQueryProcessor(), max_retries=max_retries, **replacements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 138, in _make_queries
    if not query_processor(query):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 57, in __call__
    if not self.admissible(self._kg, query):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 90, in admissible
    self._results = query.result_to_list()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 107, in result_to_list
    return itemize(self.result_text)
                   ^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 104, in result_text
    return self._extract_text_from_result(self.result)
                                          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lazy_property/__init__.py", line 27, in __get__
    result = self.method(instance)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 94, in result
    self._cache()
  File "/kgfiller/kgfiller/ai/__init__.py", line 72, in _cache
    completion = self._chat_completion_to_dict(self._chat_completion)
                                               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lazy_property/__init__.py", line 27, in __get__
    result = self.method(instance)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 49, in _chat_completion
    raise e
  File "/kgfiller/kgfiller/ai/__init__.py", line 39, in _chat_completion
    return self._chat_completion_step()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/openai.py", line 55, in _chat_completion_step
    result = openai.ChatCompletion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 220, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 531, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPConnectionPool(host='clusters.almaai.unibo.it', port=23231): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff5db9c0410>, 'Connection to clusters.almaai.unibo.it timed out. (connect timeout=600)'))
```

**Comment by gciatto** [comment]
apparently, timeouts in vicuna should be caught by means of `error.Timeout` exception type

**Comment by gciatto** [comment]
[kg-filler-almaai-vicuna-1.postmortem.zip](https://github.com/Chistera4-Expectation/kg-filler/files/14329755/kg-filler-almaai-vicuna-1.postmortem.zip)

**Comment by gciatto** [comment]
Same issue on OpenAI
[kg-filler-openai-gpt35-1.postmortem.zip](https://github.com/Chistera4-Expectation/kg-filler/files/14329788/kg-filler-openai-gpt35-1.postmortem.zip)

**Comment by gciatto** [comment]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/kgfiller/kgfiller/__main__.py", line 32, in <module>
    commit = find_instances_for_class(kg, cls, instance_queries)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 164, in find_instances_for_class
    return _make_queries(kg, queries, FindInstancesQueryProcessor(), max_retries=max_retries, **replacements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 138, in _make_queries
    if not query_processor(query):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 57, in __call__
    if not self.admissible(self._kg, query):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/strategies.py", line 90, in admissible
    self._results = query.result_to_list()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 107, in result_to_list
    return itemize(self.result_text)
                   ^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 104, in result_text
    return self._extract_text_from_result(self.result)
                                          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lazy_property/__init__.py", line 27, in __get__
    result = self.method(instance)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 94, in result
    self._cache()
  File "/kgfiller/kgfiller/ai/__init__.py", line 72, in _cache
    completion = self._chat_completion_to_dict(self._chat_completion)
                                               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lazy_property/__init__.py", line 27, in __get__
    result = self.method(instance)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/__init__.py", line 49, in _chat_completion
    raise e
  File "/kgfiller/kgfiller/ai/__init__.py", line 39, in _chat_completion
    return self._chat_completion_step()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kgfiller/kgfiller/ai/openai.py", line 55, in _chat_completion_step
    result = openai.ChatCompletion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 220, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 533, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='clusters.almaai.unibo.it', port=23231): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9412c5c50>: Failed to establish a new connection: [Errno 113] No route to host'))
```
one more error to tackle

**Comment by AndAgio** [comment]
Added openai.error.APIConnectionError to list of errors.
