### ISSUE TITLE
Rate limits poorly handled on HuggingFace

### ISSUE THREAD

**Issue by gciatto** [Chistera4-Expectation/kg-filler#3]
```
DEBUG:kgfiller:Discovered available models for chatbot 139750876993360: ['mistralai/Mixtral-8x7B-Instruct-v0.1', 'meta-llama/Llama-2-70b-chat-hf', 'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO', 'codellama/CodeLlama-70b-Instruct-hf', 'mistralai/Mistral-7B-Instruct-v0.1', 'mistralai/Mistral-7B-Instruct-v0.2', 'openchat/openchat-3.5-0106']
2024-02-19 09:39:53,698 - kgfiller - DEBUG - Selected model mistralai/Mixtral-8x7B-Instruct-v0.1 for chatbot $139750876993360
DEBUG:kgfiller:Selected model mistralai/Mixtral-8x7B-Instruct-v0.1 for chatbot $139750876993360
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:39:54,309 - kgfiller - WARNING - Rate limit exceeded, retrying in 30 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 30 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:40:24,451 - kgfiller - WARNING - Rate limit exceeded, retrying in 45 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 45 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:41:09,600 - kgfiller - WARNING - Rate limit exceeded, retrying in 68 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 68 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:42:17,255 - kgfiller - WARNING - Rate limit exceeded, retrying in 1e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 1e+02 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:43:58,663 - kgfiller - WARNING - Rate limit exceeded, retrying in 1.5e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 1.5e+02 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:46:30,876 - kgfiller - WARNING - Rate limit exceeded, retrying in 2.3e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 2.3e+02 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc0400>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc0220>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc05e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc07c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc09a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 696, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x7f1a49dc0b80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 722, in _stream_query
    raise exceptions.ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:50:18,901 - kgfiller - WARNING - Rate limit exceeded, retrying in 3.4e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 3.4e+02 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 09:56:04,372 - kgfiller - WARNING - Rate limit exceeded, retrying in 5.1e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 5.1e+02 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 10:04:40,726 - kgfiller - WARNING - Rate limit exceeded, retrying in 7.7e+02 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 7.7e+02 seconds
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
2024-02-19 10:17:32,901 - kgfiller - WARNING - Rate limit exceeded, retrying in 1.2e+03 seconds
WARNING:kgfiller:Rate limit exceeded, retrying in 1.2e+03 seconds
```

messages with internal errors should be treated adequately

**Comment by AndAgio** [comment]
Updated hugchat api to the latest version and modified the list of available models to fix the 'Internal Error' issue.
